using Asp.Versioning.ApiExplorer;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;

namespace Agent.Api.Extensions;

/// <summary>
/// Provides extension methods for configuring ReDoc API documentation middleware.
/// 提供用于配置 ReDoc API 文档中间件的扩展方法。
/// </summary>
/// <remarks>
/// ReDoc is an alternative API documentation UI to SwaggerUI. It provides a clean, 
/// three-column layout that is highly readable and professional.
/// ReDoc 是 SwaggerUI 的替代 API 文档 UI。它提供简洁的三栏布局，具有极高的可读性和专业感。
/// 
/// Integration relies on Swashbuckle.AspNetCore.ReDoc package.
/// 集成依赖于 Swashbuckle.AspNetCore.ReDoc 包。
/// </remarks>
public static class RedocExtensions
{
    /// <summary>
    /// Configures the application to use ReDoc for API documentation.
    /// 配置应用程序使用 ReDoc 进行 API 文档展示。
    /// </summary>
    /// <param name="app">The IApplicationBuilder instance. IApplicationBuilder 实例。</param>
    /// <returns>The IApplicationBuilder instance for chaining. 用于链式调用的 IApplicationBuilder 实例。</returns>
    public static IApplicationBuilder UseRedocDocumentation(this IApplicationBuilder app)
    {
        // ReDoc still requires the Swagger JSON endpoint generated by app.UseSwagger()
        // ReDoc 仍然需要由 app.UseSwagger() 生成的 Swagger JSON 端点
        app.UseSwagger();

        // Configure ReDoc UI
        // 配置 ReDoc UI
        app.UseReDoc(options =>
        {
            var provider = app.ApplicationServices.GetRequiredService<IApiVersionDescriptionProvider>();
            
            // ReDoc typically shows one version at a time. By default, we point to the latest version.
            // If multi-version support is needed in the UI, additional logic or multiple ReDoc endpoints would be required.
            // ReDoc 通常一次显示一个版本。默认情况下，我们指向最新版本。
            // 如果 UI 中需要多版本支持，则需要额外的逻辑或多个 ReDoc 端点。
            var latestVersion = provider.ApiVersionDescriptions.OrderByDescending(v => v.ApiVersion).FirstOrDefault();
            
            if (latestVersion != null)
            {
                options.SpecUrl = $"/swagger/{latestVersion.GroupName}/swagger.json";
                options.DocumentTitle = $"AgentProject API Documentation - {latestVersion.GroupName}";
            }
            
            // Set the route prefix for ReDoc. Access it via /redoc
            // 设置 ReDoc 的路由前缀。通过 /redoc 访问
            options.RoutePrefix = "redoc";
            
            // ReDoc specific configuration options
            // ReDoc 特定的配置选项
            options.ExpandResponses("200,201");
            options.RequiredPropsFirst();
            options.NoAutoAuth();
            options.HideDownloadButton();
            options.HideHostname();
        });

        return app;
    }
}
