
import {
  SquarePen,
  LayoutTemplate,
  Terminal,
  Send,
  Paperclip,
  Mic,
  ChevronDown,
  ChevronRight,
  PanelRightClose,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightOpen,
  Maximize2,
  Minimize2,
  X,
  Copy,
  Check,
  Zap,
  Cpu,
  MessageSquare,
  MoreHorizontal,
  Sparkles,
  Folder,
  FolderOpen,
  FolderPlus,
  Edit2,
  Trash2,
  Mail,
  FolderInput,
  MoreVertical,
  Plus,
  CornerUpRight,
  Brain,
  Box,
  Settings,
  User,
  LogOut,
  HelpCircle,
  CreditCard,
  FileText,
  GitMerge,
  Briefcase,
  Building2,
  Lightbulb
} from 'lucide-react';

export const Icons = {
  NewChat: SquarePen,
  Sidebar: LayoutTemplate,
  Terminal: Terminal,
  Send: Send,
  Attach: Paperclip,
  Mic: Mic,
  ChevronDown: ChevronDown,
  ChevronRight: ChevronRight,
  ClosePanelRight: PanelRightClose,
  ClosePanelLeft: PanelLeftClose,
  OpenPanelLeft: PanelLeftOpen,
  OpenPanelRight: PanelRightOpen,
  Maximize: Maximize2,
  Minimize: Minimize2,
  Close: X,
  Copy: Copy,
  Check: Check,
  Zap: Zap, 
  Cpu: Cpu,
  Chat: MessageSquare,
  More: MoreHorizontal,
  MoreVertical: MoreVertical,
  Sparkles: Sparkles,
  Folder: Folder,
  FolderOpen: FolderOpen,
  NewGroup: FolderPlus,
  Edit: Edit2,
  Trash: Trash2,
  Mail: Mail,
  MoveTo: FolderInput,
  Plus: Plus,
  ArrowRight: CornerUpRight,
  Brain: Brain,
  Box: Box,
  Settings: Settings,
  User: User,
  LogOut: LogOut,
  Help: HelpCircle,
  CreditCard: CreditCard,
  FileText: FileText,
  GitMerge: GitMerge,
  Briefcase: Briefcase,
  Building2: Building2,
  Lightbulb: Lightbulb
};
